development:
  host: <%= ENV['DB_HOST'] %>
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  encoding: utf8
  reconnect: false
  pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  host: <%= ENV['DB_HOST'] %>
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  encoding: utf8
  reconnect: false
  pool: 5